apiVersion: v1
kind: Service
metadata:
  name: my-project
spec:
  selector:
    app: my-project
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8080 # Container port
  type: NodePort  #LoadBalancer # or NodePort, depending on your needs